//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Table
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Phono { get; set; }
        public string Address { get; set; }
    }
}
